### ISSUE TITLE
Could not locate update bundle

### ISSUE THREAD

**Issue by bitomule** [jenslind/electron-gh-releases#12]
I get this error after an update is downloaded. I see the log of update downloaded but "update-downloaded" event is never fired. I've checked the folder where zip should be and it's empty but something is downloaded and removed before the crash.

The full error is:

```
Could not locate update bundle for {appname} within file:///Users/{me}/Library/Application%20Support/{appname}.ShipIt/update.nQcEUZ3/: (null) at Error (native)

```

Any idea on what could be wrong? I'm using electron-release and electron-packager to package and upload to github.

**Comment by jenslind** [comment]
Hmm, thats quite hard to debug. :)
It's an Squirrel error, https://github.com/Squirrel/Squirrel.Mac/blob/master/Squirrel/SQRLUpdater.m#L448

Wild guess:
Is your `bundleIdentifier` the same on both the running app and the downloaded?
The bundle-id is set in `info.plist`.

**Comment by bitomule** [comment]
Where's the info.plist? Thanks!

**Comment by bitomule** [comment]
Yes, bundle-id is the same in both, just different version. I've posted on squirrel mac but no answer yet :( What do you use to build your osx electron apps?

**Comment by jenslind** [comment]
I use https://github.com/maxogden/electron-packager

**Comment by bitomule** [comment]
I'm using it too, not sure where my error is. My package.json is:

```
"name": "myapp",
"productName": "myapp",
"version": "1.0.3",
"main": "main.js",
"description": "A desktop version of the myapp web app.",
"repository": {
  "url": "https://github.com/myapp/myapp-desktop"
},
"scripts": {
  "dev": "electron .",
},
"dependencies": {
  "electron-gh-releases": "^2.0.2",
  "configstore": "^1.2.1",
  "electron-builder": "^2.3.1"
},
"devDependencies": {
  "grunt": "^0.4.5",
  "grunt-electron-installer": "^1.2.0",
  "electron-packager": "^5.1.1",
  "electron-prebuilt": "^0.35.2"
}
```

**Comment by bitomule** [comment]
@jenslind where can I check the bundle id? I'm trying to find the issue in squirrel but issue seems to be in electron-gh-releases on electron-packager setup. This is how I build my osx app:

```
electron-packager ./ myapp --out=dist/osx --platform=darwin --arch=all --version=0.35.2 --app-version 1.0.3 --app-bundle-id=myapp --helper-bundle-id=myapp --overwrite=true --asar=true --icon=assets/osx/myapp.icns --prune=true --ignore=dist --sign="Developer ID Application: MyCompany."
```

**Comment by jenslind** [comment]
You can find the bundle id in the apps info.plist file.
`yourapp.app/Contents/Info.plist` the key is `CFBundleIdentifier`
As far as I know it needs to be the same on the running app and the version that its downloaded.

**Comment by bitomule** [comment]
Ok, checked and both are the same. Any idea on how can I get a better error?  Maybe --helper-bundle-id shouldn't be the same as bundle-id, asar option? Not sure what can be wrong if it works in other cases. My app is just a web wrapper.

**Comment by jenslind** [comment]
Hmm, I have no idea, do you mind linking to the repo?

**Comment by bitomule** [comment]
@jenslind sure! Thank you for your help. Here's the repo with the releases (removed some) and auto_updater.json

https://github.com/mmmelon/mmmelon-desktop

**Comment by jenslind** [comment]
Looks like the downloaded zip contains `.dmg` it needs to be the `.app`.

**Comment by bitomule** [comment]
omg... I'm stupid... I'll try changing the zip to just contain .app and post result here. Thanks @jenslind!

**Comment by bitomule** [comment]
Thanks @jenslind . It works!

**Comment by benjtinsley** [comment]
it is several years later, but I am having this issue. following the recommendation by @jenslind I have isolated the downloaded files and it is a zipped .app:
<img width="612" alt="screen shot 2018-05-11 at 12 04 34 pm" src="https://user-images.githubusercontent.com/3211091/39939645-2d3575b6-5514-11e8-8233-136abb3ec529.png">


however as @bitomule originally encountered, the updater pulls the files down, but instantly deletes them with the error:

```
2018-05-11 12:02:55.640 Electron[3283:95513] Download completed to: file:///path/to/Caches/com.github.electron.ShipIt/update.a74SCao/0.0.6.zip
{ Error: Could not locate update bundle for com.github.electron within file:///path/to/Caches/com.github.electron.ShipIt/update.a74SCao/ code: 2, domain: 'SQRLUpdaterErrorDomain' }
```

I am running on local, which is why it is putting it in `com.github.electron` instead of the proper bundle id of my app. if running the distributed app, I encounter the same problem.


PS - this is not an electron-gh-releases issue on my end, as far as I can tell. I am mostly just adding this here since this was the only relatable issue I encountered online

**Comment by mike-seekwell** [comment]
@benjtinsley Did you end up figuring this out? I'm getting the same error. My .zip only contains the .app file so it's not the issue noted earlier.

**Comment by benjtinsley** [comment]
@mike-seekwell yes, the error was i had an app that was not properly signed. mac was downloading, checking the verification, seeing it was unverified and then silently deleting the file with no feedback. i installed [RB App Checker Lite](https://itunes.apple.com/us/app/rb-app-checker-lite/id519421117?mt=12) to verify the app to ensure my certificates were signing correctly. once that was done, i was sure to have a verified version of the app installed and then tried running the autoupdater with a verified revision and it worked. 

electron development is quite the diaspora so it's often hard to pinpoint where the real issue lies but this was it for me. it had nothing to do with this project at all, so if we want to close this issue if others are finding success with my learnings, please do.

EDIT: whoops looks like it's already closed, yay

**Comment by mike-seekwell** [comment]
Yeah, I was trying to get it to work on my dev version (i.e. `npm start`), but couldn't get it to work. When I tried the packaged version, autoupdating worked.

**Comment by benjtinsley** [comment]
@mike-seekwell gotcha, must be something about `com.github.electron` being the bundle ID on local. i'm sure there's a better way to verify this in development mode, but i haven't found it. sort of a bummer that it takes 10-ish mins to check your work :shrug:
